[versions]
agp = "8.10.1"
dagger = "2.57.2"
daggerCompiler = "2.57.2"
datastorePreferences = "1.2.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.1"
lifecycleProcess = "2.10.0"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.1.4"
material3WindowSizeClass = "1.4.0"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
roomCommonJvm = "2.8.4"
roomRuntimeAndroid = "2.8.4"
preference = "1.2.0"
sentryAndroid = "8.31.0"
sentryAndroidFragment = "8.31.0"
window = "1.5.1"
workRuntime = "2.11.0"
hiltCommon = "1.3.0"
gson = "2.10.1"
hilt = "2.57.2"
hiltWork = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "coreKtx" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastorePreferences" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCommonJvm" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomCommonJvm" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCommonJvm" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerCompiler" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
google-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
androidx-hilt-work-alias = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
sentry-android-fragment = { module = "io.sentry:sentry-android-fragment", version.ref = "sentryAndroidFragment" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentryAndroid" }
sentry-android-navigation = { module = "io.sentry:sentry-android-navigation", version.ref = "sentryAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
